server:
  port: 8080

spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: spring
            client-id: gateway-client
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,read,write
        provider:
            spring:
            issuer-uri: http://oauth-server:9000
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://oauth-server:9000/oauth2/token
            jwk-set-uri: http://oauth-server:9000/oauth2/jwks
            user-info-uri: http://oauth-server:9000/userinfo
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: oauth-server
          uri: http://oauth-server:9000
          predicates:
            - Path=/oauth2/**
            - Path=/.well-known/**

        - id: catalogo-service
          uri: http://micro-catalogo:8080
          predicates:
            - Path=/api/catalogo/**
          filters:
            - StripPrefix=2

        - id: sucursal-service
          uri: http://micro-sucursal:8080
          predicates:
            - Path=/api/sucursal/**
          filters:
            - StripPrefix=2

        - id: cliente-service
          uri: http://micro-cliente:8080
          predicates:
            - Path=/api/cliente/**
          filters:
            - StripPrefix=2

        - id: ventas-service
          uri: http://micro-ventas:8080
          predicates:
            - Path=/api/ventas/**
          filters:
            - StripPrefix=2

        - id: reporte-service
          uri: http://micro-reporte:8080
          predicates:
            - Path=/api/reporte/**
          filters:
            - StripPrefix=2

        - id: inventario-service
          uri: http://micro-inventario:8080
          predicates:
            - Path=/api/inventario/**
          filters:
            - StripPrefix=2

        # Frontend route - must be LAST (catch-all)
        - id: frontend-service
          uri: http://frontend:80
          predicates:
            - Path=/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
